name: Building binary files
on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'
permissions:
  contents: write
jobs:
  run-bash-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Building binary files
        run: bash scripts/build_binary.sh
      - name: Commit and push if it changed
        run: |
          git diff
          git config --global user.email "github-actions[bot]@example.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit --amend --no-edit
          git push -f
