name: Your Github Workflow name
on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *'
permissions:
  contents: write
jobs:
  run-bash-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build rulesets
        run: |
          chmod +x scripts/build_ads.sh
          scripts/build_ads.sh
      - name: Commit and push if it changed
        run: |
          git diff
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add .
          git commit -m "Update data files"
          git push
